# Generated by Django 5.2 on 2025-05-21 21:37

import asistent.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anónimo', max_length=150)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(default='jRQCdNatoD6NGRoYqMI8GL7XH', max_length=25, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('information', models.TextField(blank=True, null=True)),
                ('link_url', models.TextField(blank=True, null=True)),
                ('frecuency', models.IntegerField(default=0)),
                ('document', models.FileField(blank=True, max_length=120, null=True, upload_to=asistent.models.set_pdfDB_path)),
                ('image', models.ImageField(blank=True, max_length=120, null=True, upload_to=asistent.models.set_imgDB_path)),
                ('tags', models.TextField(blank=True, help_text='Palabras Clave. Separar por comas', null=True)),
                ('last_modification', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='asistent.categorias')),
            ],
            options={
                'verbose_name': 'Base de Datos',
                'verbose_name_plural': 'Bases de Datos',
            },
        ),
        migrations.CreateModel(
            name='galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, max_length=120, null=True, upload_to=asistent.models.set_imgs_path)),
                ('description', models.TextField(blank=True, null=True)),
                ('uuid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistent.database', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Galeria',
                'verbose_name_plural': 'Galerias',
            },
        ),
        migrations.CreateModel(
            name='Mapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('coords', models.TextField(blank=True, help_text='Coordenadas JSON del mapa', null=True)),
                ('door', models.CharField(blank=True, help_text='Coordenadas de la puerta separadas por comas', max_length=255, null=True)),
                ('tags', models.TextField(blank=True, help_text='Palabras Clave. Separar por comas', null=True)),
                ('is_marker', models.BooleanField(default=False, help_text='Para los marcadores de imagen')),
                ('hide_name', models.BooleanField(default=False)),
                ('size_marker', models.CharField(default='0.05', max_length=4)),
                ('otheraction', models.TextField(blank=True, help_text='Acciones adicionales', null=True)),
                ('uuid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='asistent.database', to_field='uuid')),
            ],
            options={
                'verbose_name': 'Mapa',
                'verbose_name_plural': 'Mapa',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, max_length=120, null=True, upload_to=asistent.models.set_imgProfile_path)),
                ('password_update', models.DateField(blank=True, null=True)),
                ('user_token', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
